config/routes.rb
Demo::Application.routes.draw do
  resources :requests

  resources :volunteers

  resources :voters

end

app/models/request.rb
class Request < ActiveRecord::Base
  attr_accessible :address, :foursquare, :geo_radius, :geo_start, :instagram, :keyword, :time_end, :time_start, :twitter
end

app/models/volunteer.rb
class Volunteer < ActiveRecord::Base
  attr_accessible :address, :assigned_voters, :county, :email, :hours_remaining, :hours_total, :name, :phone, :start_date
end

app/models/voter.rb
class Voter < ActiveRecord::Base
  attr_accessible :address, :age, :county, :email, :eventbrite, :foursquare, :name, :party_affiliation, :phone, :tweets, :voter_confirmed, :voter_registered, :voter_sentiment
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  # GET /requests
  # GET /requests.json
  def index
    @requests = Request.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @requests }
    end
  end

  # GET /requests/1
  # GET /requests/1.json
  def show
    @request = Request.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @request }
    end
  end

  # GET /requests/new
  # GET /requests/new.json
  def new
    @request = Request.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @request }
    end
  end

  # GET /requests/1/edit
  def edit
    @request = Request.find(params[:id])
  end

  # POST /requests
  # POST /requests.json
  def create
    @request = Request.new(params[:request])

    respond_to do |format|
      if @request.save
        format.html { redirect_to @request, notice: 'Request was successfully created.' }
        format.json { render json: @request, status: :created, location: @request }
      else
        format.html { render action: "new" }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /requests/1
  # PUT /requests/1.json
  def update
    @request = Request.find(params[:id])

    respond_to do |format|
      if @request.update_attributes(params[:request])
        format.html { redirect_to @request, notice: 'Request was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
  def destroy
    @request = Request.find(params[:id])
    @request.destroy

    respond_to do |format|
      format.html { redirect_to requests_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/volunteers_controller.rb
class VolunteersController < ApplicationController
  # GET /volunteers
  # GET /volunteers.json
  def index
    @volunteers = Volunteer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @volunteers }
    end
  end

  # GET /volunteers/1
  # GET /volunteers/1.json
  def show
    @volunteer = Volunteer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @volunteer }
    end
  end

  # GET /volunteers/new
  # GET /volunteers/new.json
  def new
    @volunteer = Volunteer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @volunteer }
    end
  end

  # GET /volunteers/1/edit
  def edit
    @volunteer = Volunteer.find(params[:id])
  end

  # POST /volunteers
  # POST /volunteers.json
  def create
    @volunteer = Volunteer.new(params[:volunteer])

    respond_to do |format|
      if @volunteer.save
        format.html { redirect_to @volunteer, notice: 'Volunteer was successfully created.' }
        format.json { render json: @volunteer, status: :created, location: @volunteer }
      else
        format.html { render action: "new" }
        format.json { render json: @volunteer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /volunteers/1
  # PUT /volunteers/1.json
  def update
    @volunteer = Volunteer.find(params[:id])

    respond_to do |format|
      if @volunteer.update_attributes(params[:volunteer])
        format.html { redirect_to @volunteer, notice: 'Volunteer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @volunteer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /volunteers/1
  # DELETE /volunteers/1.json
  def destroy
    @volunteer = Volunteer.find(params[:id])
    @volunteer.destroy

    respond_to do |format|
      format.html { redirect_to volunteers_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/voters_controller.rb
class VotersController < ApplicationController
  # GET /voters
  # GET /voters.json
  def index
    @voters = Voter.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @voters }
    end
  end

  # GET /voters/1
  # GET /voters/1.json
  def show
    @voter = Voter.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @voter }
    end
  end

  # GET /voters/new
  # GET /voters/new.json
  def new
    @voter = Voter.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @voter }
    end
  end

  # GET /voters/1/edit
  def edit
    @voter = Voter.find(params[:id])
  end

  # POST /voters
  # POST /voters.json
  def create
    @voter = Voter.new(params[:voter])

    respond_to do |format|
      if @voter.save
        format.html { redirect_to @voter, notice: 'Voter was successfully created.' }
        format.json { render json: @voter, status: :created, location: @voter }
      else
        format.html { render action: "new" }
        format.json { render json: @voter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /voters/1
  # PUT /voters/1.json
  def update
    @voter = Voter.find(params[:id])

    respond_to do |format|
      if @voter.update_attributes(params[:voter])
        format.html { redirect_to @voter, notice: 'Voter was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @voter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /voters/1
  # DELETE /voters/1.json
  def destroy
    @voter = Voter.find(params[:id])
    @voter.destroy

    respond_to do |format|
      format.html { redirect_to voters_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/volunteers_helper.rb
module VolunteersHelper
end

app/helpers/voters_helper.rb
module VotersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a href="#" class="brand"> Sunshine</a>
          <ul class="nav">
            <li><%= link_to "Voters", voters_path%></li>
            <li><%= link_to "Volunteers", volunteers_path%></li>
            <li><%= link_to "Request Data", requests_path%></li>
            <li><%= link_to "Hot Spots" %></li>
      </div>
    </div>
  </div>
  <div class="container">
<%= yield %>

</body>
</html>

app/views/requests/_form.html.erb
<%= form_for(@request) do |f| %>
  <% if @request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
      <% @request.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :time_start %><br />
    <%= f.text_field :time_start %>
  </div>
  <div class="field">
    <%= f.label :time_end %><br />
    <%= f.text_field :time_end %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :geo_start %><br />
    <%= f.text_field :geo_start %>
  </div>
  <div class="field">
    <%= f.label :geo_radius %><br />
    <%= f.text_field :geo_radius %>
  </div>
  <div class="field">
    <%= f.label :keyword %><br />
    <%= f.text_area :keyword %>
  </div>
  <div class="field">
    <%= f.label :twitter %><br />
    <%= f.check_box :twitter %>
  </div>
  <div class="field">
    <%= f.label :foursquare %><br />
    <%= f.check_box :foursquare %>
  </div>
  <div class="field">
    <%= f.label :instagram %><br />
    <%= f.check_box :instagram %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/requests/edit.html.erb
<h1>Editing request</h1>

<%= render 'form' %>

<%= link_to 'Show', @request %> |
<%= link_to 'Back', requests_path %>

app/views/requests/index.html.erb
<div class="page-header">
  <h2> All Requests </h2> 
  <%= link_to 'Add a New request', new_request_path, class: "btn btn-primary" %>
</div>


<% @requests.each do |request| %>
<div class="request">
  <strong><%= request.name %></strong>
  <p><%= request.address %></p> 
  <div class="meta">
    <p><%= link_to"This request was added to Sunshine " + time_ago_in_words(request.created_at) + " ago", request%></p>
    <%= link_to "Show", request %> |
    <span class="admin">
      <%= link_to "Edit", edit_request_path(request) %> |
      <%= link_to "Delete", request, method: :delete, data: {confirm: "Do you REALLY want to delete this request?!?"} %>
    </span>
  </div>
</div>
<% end %>



<!--<h1>Listing requests</h1>

<table>
  <tr>
    <th>Time start</th>
    <th>Time end</th>
    <th>Address</th>
    <th>Geo start</th>
    <th>Geo radius</th>
    <th>Keyword</th>
    <th>Twitter</th>
    <th>Foursquare</th>
    <th>Instagram</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @requests.each do |request| %>
  <tr>
    <td><%= request.time_start %></td>
    <td><%= request.time_end %></td>
    <td><%= request.address %></td>
    <td><%= request.geo_start %></td>
    <td><%= request.geo_radius %></td>
    <td><%= request.keyword %></td>
    <td><%= request.twitter %></td>
    <td><%= request.foursquare %></td>
    <td><%= request.instagram %></td>
    <td><%= link_to 'Show', request %></td>
    <td><%= link_to 'Edit', edit_request_path(request) %></td>
    <td><%= link_to 'Destroy', request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Request', new_request_path %>

app/views/requests/new.html.erb
<h1>New request</h1>

<%= render 'form' %>

<%= link_to 'Back', requests_path %>

app/views/requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Time start:</b>
  <%= @request.time_start %>
</p>

<p>
  <b>Time end:</b>
  <%= @request.time_end %>
</p>

<p>
  <b>Address:</b>
  <%= @request.address %>
</p>

<p>
  <b>Geo start:</b>
  <%= @request.geo_start %>
</p>

<p>
  <b>Geo radius:</b>
  <%= @request.geo_radius %>
</p>

<p>
  <b>Keyword:</b>
  <%= @request.keyword %>
</p>

<p>
  <b>Twitter:</b>
  <%= @request.twitter %>
</p>

<p>
  <b>Foursquare:</b>
  <%= @request.foursquare %>
</p>

<p>
  <b>Instagram:</b>
  <%= @request.instagram %>
</p>


<%= link_to 'Edit', edit_request_path(@request) %> |
<%= link_to 'Back', requests_path %>

app/views/volunteers/_form.html.erb
<%= form_for(@volunteer) do |f| %>
  <% if @volunteer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@volunteer.errors.count, "error") %> prohibited this volunteer from being saved:</h2>

      <ul>
      <% @volunteer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :county %><br />
    <%= f.text_field :county %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :hours_total %><br />
    <%= f.text_field :hours_total %>
  </div>
  <div class="field">
    <%= f.label :hours_remaining %><br />
    <%= f.text_field :hours_remaining %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br />
    <%= f.text_field :start_date %>
  </div>
  <div class="field">
    <%= f.label :assigned_voters %><br />
    <%= f.text_area :assigned_voters %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/volunteers/edit.html.erb
<h1>Editing volunteer</h1>

<%= render 'form' %>

<%= link_to 'Show', @volunteer %> |
<%= link_to 'Back', volunteers_path %>

app/views/volunteers/index.html.erb
<div class="page-header">
  <h2> All Volunteers </h2> 
  <%= link_to 'Add a New volunteer', new_volunteer_path, class: "btn btn-primary" %>
</div>


<% @volunteers.each do |volunteer| %>
<div class="volunteer">
  <strong><%= volunteer.name %></strong>
  <p><%= volunteer.address %></p> 
  <div class="meta">
    <p><%= link_to"This volunteer was added to Sunshine " + time_ago_in_words(volunteer.created_at) + " ago", volunteer%></p>
    <%= link_to "Show", volunteer %> |
    <span class="admin">
      <%= link_to "Edit", edit_volunteer_path(volunteer) %> |
      <%= link_to "Delete", volunteer, method: :delete, data: {confirm: "Do you REALLY want to delete this volunteer?!?"} %>
    </span>
  </div>
</div>
<% end %>

app/views/volunteers/new.html.erb
<h1>New volunteer</h1>

<%= render 'form' %>

<%= link_to 'Back', volunteers_path %>

app/views/volunteers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @volunteer.name %>
</p>

<p>
  <b>Address:</b>
  <%= @volunteer.address %>
</p>

<p>
  <b>County:</b>
  <%= @volunteer.county %>
</p>

<p>
  <b>Email:</b>
  <%= @volunteer.email %>
</p>

<p>
  <b>Phone:</b>
  <%= @volunteer.phone %>
</p>

<p>
  <b>Hours total:</b>
  <%= @volunteer.hours_total %>
</p>

<p>
  <b>Hours remaining:</b>
  <%= @volunteer.hours_remaining %>
</p>

<p>
  <b>Start date:</b>
  <%= @volunteer.start_date %>
</p>

<p>
  <b>Assigned voters:</b>
  <%= @volunteer.assigned_voters %>
</p>


<%= link_to 'Edit', edit_volunteer_path(@volunteer) %> |
<%= link_to 'Back', volunteers_path %>

app/views/voters/_form.html.erb
<%= form_for(@voter) do |f| %>
  <% if @voter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@voter.errors.count, "error") %> prohibited this voter from being saved:</h2>

      <ul>
      <% @voter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :county %><br />
    <%= f.text_field :county %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :age %><br />
    <%= f.text_field :age %>
  </div>
  <div class="field">
    <%= f.label :party_affiliation %><br />
    <%= f.text_field :party_affiliation %>
  </div>
  <div class="field">
    <%= f.label :voter_registered %><br />
    <%= f.check_box :voter_registered %>
  </div>
  <div class="field">
    <%= f.label :voter_confirmed %><br />
    <%= f.check_box :voter_confirmed %>
  </div>
  <div class="field">
    <%= f.label :voter_sentiment %><br />
    <%= f.text_field :voter_sentiment %>
  </div>
  <div class="field">
    <%= f.label :tweets %><br />
    <%= f.text_area :tweets %>
  </div>
  <div class="field">
    <%= f.label :foursquare %><br />
    <%= f.text_area :foursquare %>
  </div>
  <div class="field">
    <%= f.label :eventbrite %><br />
    <%= f.text_area :eventbrite %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/voters/edit.html.erb
<h1>Editing voter</h1>

<%= render 'form' %>

<%= link_to 'Show', @voter %> |
<%= link_to 'Back', voters_path %>

app/views/voters/index.html.erb
<div class="page-header">
  <h2> All Voters </h2> 
  <%= link_to 'Add a New Voter', new_voter_path, class: "btn btn-primary" %>
</div>


<% @voters.each do |voter| %>
<div class="voter">
  <strong><%= voter.name %></strong>
  <p><%= voter.address %></p> 
  <div class="meta">
    <p><%= link_to"This voter was added to Sunshine " + time_ago_in_words(voter.created_at) + " ago", voter%></p>
    <%= link_to "Show", voter %> |
    <span class="admin">
      <%= link_to "Edit", edit_voter_path(voter) %> |
      <%= link_to "Delete", voter, method: :delete, data: {confirm: "Do you REALLY want to delete this voter?!?"} %>
    </span>
  </div>
</div>
<% end %>

app/views/voters/new.html.erb
<h1>New voter</h1>

<%= render 'form' %>

<%= link_to 'Back', voters_path %>

app/views/voters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @voter.name %>
</p>

<p>
  <b>County:</b>
  <%= @voter.county %>
</p>

<p>
  <b>Address:</b>
  <%= @voter.address %>
</p>

<p>
  <b>Email:</b>
  <%= @voter.email %>
</p>

<p>
  <b>Phone:</b>
  <%= @voter.phone %>
</p>

<p>
  <b>Age:</b>
  <%= @voter.age %>
</p>

<p>
  <b>Party affiliation:</b>
  <%= @voter.party_affiliation %>
</p>

<p>
  <b>Voter registered:</b>
  <%= @voter.voter_registered %>
</p>

<p>
  <b>Voter confirmed:</b>
  <%= @voter.voter_confirmed %>
</p>

<p>
  <b>Voter sentiment:</b>
  <%= @voter.voter_sentiment %>
</p>

<p>
  <b>Tweets:</b>
  <%= @voter.tweets %>
</p>

<p>
  <b>Foursquare:</b>
  <%= @voter.foursquare %>
</p>

<p>
  <b>Eventbrite:</b>
  <%= @voter.eventbrite %>
</p>


<%= link_to 'Edit', edit_voter_path(@voter) %> |
<%= link_to 'Back', voters_path %>